const teamMembers = [
    {
        name: "MR. N. CHANDRASEKARAN",
        designation: "Chairman",
        description: "Mr. N. Chandrasekaran serves as Chairman of the board of Tata Sons, the holding company and promoter of more than 100 Tata operating companies with aggregate annual revenues of more than US $150 billion. He joined the board of Tata Sons in October 2016 and was appointed Chairman in January 2017. His appointment as Chairman of Tata Sons followed a 30-year career at Tata Consulting Services. Mr. Chandrasekaran rose through the ranks to become the CEO and under his leadership, TCS consolidated its position as the largest private sector employer in India and India’s most valuable company.Since he has taken over as Chairman of Tata Sons, Mr. Chandrasekaran has been driving transformation of the group towards digital, sustainability and supply chain resilience. The group has forayed into new businesses including electronics manufacturing, semiconductor, EV battery manufacturing, consumer internet platform, and mobile technology for 5G. The Tata group has expanded its aviation presence with the acquisition of Air India and is building a large global airline. Mr. Chandrasekaran was conferred with the Padma Bhushan, one of the highest civilian awards in India, in the field of trade and industry in 2022. The French Government conferred him with Légion d’Honneur, the highest civilian award in France for his outstanding business successes and decisive contribution to strengthening Indo-French economic ties. President Eisenhower Global Award for Leadership by the Business Council for International Understanding (BCIU) was conferred to him in 2022. Mr. Chandrasekaran is the Co-Chair of the US India CEO Forum. He is on the Board of Governors of New York Academy of Sciences, elected as an international member of the United States National Academy of Engineering (NAE), a member of the UTokyo Global Navigation Board, the Mitsubishi’s International Advisory Committee and International Advisory Council of Singapore’s Economic Development Board. He is the Chairman of Indian Institute of Management, Lucknow as well as the President of the Court at Indian Institute of Science, Bengaluru. Mr. Chandrasekaran is also a member of the Stanford Doer School for Sustainability Advisory Council and the MIT CEO Advisory Board. Mr. Chandrasekaran is also the author of Bridgital Nation, a groundbreaking book on harnessing technological disruptions to bring Indians closer to their dreams.",
        imgSrc: "./img/Tatahome/BOD/Artboard 3Aunty.webp"  // Add image URL here
    },
    {
        name: "MR. P. B. BALAJI",
        designation: "(Non Independent) Director",
        description: "Mr. P.B. Balaji has been serving as the Group Chief Financial Officer of Tata Motors Limited (“TML”) since November 2017. He is a member of the Executive Committee of TML and plays a key role in TML Group’s profitable and sustainable growth journey. He is also on the boards of Jaguar Land Rover, Tata Motors Finance Group Tata Technologies, and Tata Consumer Products Ltd. With nearly three decades of experience in the corporate sector, Mr. Balaji is a seasoned global finance professional who has worked across the FMCG and Automotive industries. He started his career at Unilever in 1995, where he held different corporate finance and supply chain positions in India, Singapore, UK, and Switzerland, Prior to joining Tata Motors, he served as the Chief Financial Officer of Hindustan Unilever. Mr. Balaji holds a post-graduate degree in management from the Indian Institute of Management, Calcutta, and is an alumnus of the Indian Institute of Technology, Chennai.",
        imgSrc: "./img/Tatahome/BOD/Artboard 4Aunty.webp"  // Add image URL here
    },
    {
        name: "MR. SIRAJ CHAUDHRY",
        designation: "Independent Director",
        description: "Mr. Siraj Chaudhry is a renowned industry expert, innovator, thought leader, and prominent voice in the agriculture and food industry. He has collaborated extensively with various sectors, including the government, social sector, and industry, on various transformational and nation-building projects. He holds a degree in B.Com (Hons.) from Delhi University, Masters in International Business from Indian Institute of Foreign Trade With over 36 years of experience in building, acquiring, divesting, and turning around businesses, Mr. Chaudhry currently serves as the Chief Advisor and Non-Executive Chairman for SATS India. Previously, he was the Managing Director & CEO of NCML, where he played a pivotal role in expanding the company’s footprint across the country and diversifying its operations, establishing it as a trusted and preferred agri-supply chain and solutions provider. He was also the Chairman of Cargill India, the Indian arm of Cargill Inc., where he led the build and expansion of Cargill’s food business in India, making it a leading player in edible oils, flour, corn products, and food ingredients. During his tenure, Cargill’s animal nutrition business and global business services footprint in India saw significant growth. Mr. Chaudhry is credited with spearheading Cargill’s efforts in edible oil fortification, which was recognized by Fortune Magazine as a Change the World activity. In addition to serving as a Non- Executive Director & Chairman Board of NCML, Mr. Chaudhry is an Independent Director on the boards f several companies, including Tata Consumers Products Ltd., Tata Coffee Ltd., Dhanuka Agritech Ltd., Jubilant Ingrevia Ltd, Triveni Engineering and Industries Ltd, Bikaji Foods International Ltd., Dhanuka Agritech Ltd., and Carrier Airconditioning & Refrigeration Ltd, SATS (India) Co. Pvt Ltd, Air India SATS Airport Services Pvt Ltd. He is also a member of the non-statutory advisory council of AB InBev, India, Louis Dreyfus Company, and Stanton Chase India Mr. Chaudhry has previously served as an Independent Director on the Board of IndusInd Bank and as a member of CDC Group plc (now BII) Food & Agriculture Advisory Council. He has chaired the National Committee on Food Processing and served as the Co-chair of the National Committee for Agriculture at FICCI. Mr. Chaudhry has also chaired the Agriculture and Food Committees at the American Chamber of Commerce and US India Business Council in India.",
        imgSrc: "./img/Tatahome/BOD/Artboard 5Aunty.webp"  // Add image URL here
    },
    {
        name: "MR. BHARAT PURI",
        designation: "Independent Director",
        description:"Mr. Bharat Puri is the Managing Director of Pidilite Industries Limited since April 2015, having first joined the Board of Pidilite Industries Ltd as an Independent Director in 2008. With a proven track record as a successful global business leader, he has effectively built, motivated, and directed diverse teams across various regions in both developed and developing markets. He is graduate in Commerce from Punjab University and holds post-graduate diploma in Management (MBA) from IIM, Ahmedabad. Mr. Puri’s professional journey began at Asian Paints in 1982, where he started as a Sales & Marketing executive and eventually rose to the position of Head of Sales & Marketing. In 1998, he transitioned to Cadbury India, serving as Director of Sales & Marketing before being appointed as its Managing Director in 2002. Throughout his career, he has held several senior leadership positions in Sales, Marketing, and General Management at both regional and global levels. His last appointment was as the Global President of Chocolates, Gum, and Candy for Mondelez International.",
        imgSrc: "./img/Tatahome/BOD/Artboard 7Aunty.webp"  // Add image URL here
    },
    {
        name: "MS. SHIKHA SHARMA",
        designation: "Independent Director",
        description: "Ms. Shikha Sharma holds a degree in B.A (Hons.) in Economics, post-graduate diploma in Software Technology from National Center for Software Technology and Post Graduate Diploma in Management from IIM, Ahmedabad. With a wealth of experience in banking and insurance, she boasts an impressive track record. During her tenure, she successfully transformed Axis Bank Limited from a predominantly corporate lender to a bank with a robust retail deposit franchise and a well-balanced lending book. Ms. Sharma embarked on her career with ICICI Bank in 1980. She served as the MD and CEO of ICICI Personal Financial Services from May 1998 to December 2000. Subsequently, she held the position of Managing Director and CEO at ICICI Prudential Life Insurance Company from December 2000 to June 2009. She later became the Managing Director and CEO of Axis Bank from June 2009 to December 2018. Ms. Sharma has earned numerous accolades, including the CNBC TV18 Outstanding Businesswoman of the year, AIMA JRD TATA Corporate Leadership, and Business Standard’s Banker of the Year. She has also been recognized as one of the Top 20 Women in Finance-by-Finance Asia and one of the 50 most powerful women in business by Fortune. Ms. Sharma serves on the board of directors for several publicly listed companies, including Tata Consumer Products Limited, Tech Mahindra Limited, Mahindra & Mahindra Limited, Dr. Reddy’s Laboratories Limited, and Piramal Enterprises Limited and Mahindra Electric Automobile Limited. Additionally, she is an advisor /consultant to Piramal Enterprises Limited, Billionbrains Garage Ventures Private Limited, Bahaar Foundation – a unit of Akshati Charitable Trust, andGoogle India Digital Services Pvt Ltd and McKinsey & Company Singapore Pte Ltd. She is also a member of the Board of Governors of IIM, Lucknow.",
        imgSrc: "./img/Tatahome/BOD/Artboard 9Aunty.webp"  // Add image URL here
    },
    {
        name: "DR. K. P. KRISHNAN",
        designation: "Independent Director",
        description: "Dr. K.P. Krishnan retired from the Indian Administrative Service (IAS) on December 31st, 2019, after serving for 37 years. Through his career, he held various positions in the Government of Karnataka, the Government of India, and the World Bank, serving in departments dealing with agriculture, co-operatives, marketing, urban development and infrastructure, commercial taxes, and finance. He also held field positions such as District Collector Mangalore. During his time in the Government of India, he served as Secretary of the Ministry of Skill Development and Entrepreneurship from February 1st, 2017, to December 31st, 2019, as Additional Secretary of the Department of Land Resources, Ministry of Rural Development (2014-2017), Additional Secretary of the Department of Economic Affairs, Ministry of Finance (2013-2014), Secretary of the Prime Minister’s Economic Advisory Council (2010-2012), and Joint Secretary of the Department of Economic Affairs, Ministry of Finance (2005-2010). In these roles, he served on the boards of corporations, banks, and statutory regulatory authorities. Dr. Krishnan has also been actively involved in research and academia throughout his government career. He has been a visiting faculty member at various institutions, including IIM Bangalore, ISB, and Ashoka University, and was the Bok Visiting Professor of Regulation at the University of Pennsylvania Law School in 2012-13. He served as the IEPF Chair Professor of Economics at the National Council of Applied Economic Research (NCAER) in New Delhi from August 7th, 2020, to December 31st, 2021, and is currently an Honorary Research Professor at the Centre for Policy Research (CPR) in New Delhi. Dr. Krishnan is also an Independent Director on the Boards of Shriram Capital Private Limited and Dr. Reddy’s Laboratories Limited. He studied Economics at St. Stephens College and Law at the Campus Law Centre, University of Delhi, and earned his FPM (Ph.D.) in Economics at IIM Bangalore’s 2003 graduation ceremony.",
        imgSrc: "./img/Tatahome/BOD/Artboard 10Aunty.webp"  // Add image URL here
    },
    // Add more team member objects here
    {
        name: "MR. SIRAJ CHAUDHRY",
        designation: "Independent Director",
        description: "Mr. Siraj Chaudhry is a renowned industry expert, innovator, thought leader, and prominent voice in the agriculture and food industry. He has collaborated extensively with various sectors, including the government, social sector, and industry, on various transformational and nation-building projects. He holds a degree in B.Com (Hons.) from Delhi University, Masters in International Business from Indian Institute of Foreign Trade With over 36 years of experience in building, acquiring, divesting, and turning around businesses, Mr. Chaudhry currently serves as the Chief Advisor and Non-Executive Chairman for SATS India. Previously, he was the Managing Director & CEO of NCML, where he played a pivotal role in expanding the company’s footprint across the country and diversifying its operations, establishing it as a trusted and preferred agri-supply chain and solutions provider. He was also the Chairman of Cargill India, the Indian arm of Cargill Inc., where he led the build and expansion of Cargill’s food business in India, making it a leading player in edible oils, flour, corn products, and food ingredients. During his tenure, Cargill’s animal nutrition business and global business services footprint in India saw significant growth. Mr. Chaudhry is credited with spearheading Cargill’s efforts in edible oil fortification, which was recognized by Fortune Magazine as a Change the World activity. In addition to serving as a Non- Executive Director & Chairman Board of NCML, Mr. Chaudhry is an Independent Director on the boards f several companies, including Tata Consumers Products Ltd., Tata Coffee Ltd., Dhanuka Agritech Ltd., Jubilant Ingrevia Ltd, Triveni Engineering and Industries Ltd, Bikaji Foods International Ltd., Dhanuka Agritech Ltd., and Carrier Airconditioning & Refrigeration Ltd, SATS (India) Co. Pvt Ltd, Air India SATS Airport Services Pvt Ltd. He is also a member of the non-statutory advisory council of AB InBev, India, Louis Dreyfus Company, and Stanton Chase India Mr. Chaudhry has previously served as an Independent Director on the Board of IndusInd Bank and as a member of CDC Group plc (now BII) Food & Agriculture Advisory Council. He has chaired the National Committee on Food Processing and served as the Co-chair of the National Committee for Agriculture at FICCI. Mr. Chaudhry has also chaired the Agriculture and Food Committees at the American Chamber of Commerce and US India Business Council in India.",
        imgSrc: "./img/Tatahome/BOD/Artboard 11Aunty.webp"  // Add image URL here
    },
    {
        name: "MR. DAVID CREAN",
        designation: "Independent Director",
        description: "Mr. David Crean is a highly accomplished and experienced professional in the food industry with over 35 years of expertise in leadership, talent development, innovation, research and development, science, quality management, and food safety. He is graduated with a BA (Hons.) Degree in Applied Biology from Liverpool Polytechnic. He held multiple senior leadership positions at Mars Incorporated, including, when he retired, the dual roles of Vice President of Corporate R&D and Chief Science Officer, where he contributed significantly to the Company’s strategy. Throughout his career, he led business growth initiatives, established global technology and research platforms,and most recently established various governance processes and performance standards for Mars’ global businesses. He launched over 70 Mars products in multiple geographies and drove profitable business growth across emerging and developed markets. Mr. Crean’s passion and leadership have guided Mars’ highly principled approach to science, research practices, policies, innovation, quality and food safety standards. Mr. Crean’s contributions extend beyond Mars as he participated in many events organised by the United Nations FAO and WHO while advocating for food security and safety. Since he retired from Mars in 2021, he has continued to share his knowledge and expertise, serving as Chair of the Global Food Safety Initiatives (GFSI) Science and Technology Advisory Group and advising numerous global businesses and start-ups.",
        imgSrc: "./img/Tatahome/BOD/Artboard 12Aunty.webp" 
    },
    {
        name: "MR. SUNIL D’SOUZA",
        designation: "Managing Director & CEO",
        description: "Mr. Sunil D’Souza has been serving as the Managing Director & Chief Executive Officer of Tata Consumer Products since April 2020. Prior to this, he held the position of Managing Director at Whirlpool India Ltd. for over four years and had a significant contribution in transforming the Whirlpool business in India. He has also worked with PepsiCo for almost 15 years, where he held various leadership positions, managing the commercial aspects of the company’s food and beverage portfolio, and steering the business in a large cluster of Asian countries. Mr. D’Souza started his career with Hindustan Unilever in 1993 and has 30 years of extensive experience in the consumer products sector with a strong emphasis on strategy, growth, and execution.In addition to his current role as Managing Director & Chief Executive Officer of the Company, he is also a Director on the Board of Tata Starbucks Limited, Capital Foods Private Limited, NourishCo Beverages Limited, Tata Consumer Soulfull Private Limited, Organic India Private Limited and several of Tata Consumer Products’ overseas subsidiaries. Mr. D’Souza holds a degree in engineering from the University of Madras and is an alumnus of the Indian Institute of Management, Calcutta (IIM-C).   ",
        imgSrc: "./img/Tatahome/BOD/Artboard 13Aunty.webp"
    },
    // Example: { name: "Jane Doe", designation: "CEO", description: "Description here", imgSrc: "image_url" }
];
const teamMembers2 = [
    {
        name: "MR. N. CHANDRASEKARAN",
        designation: "Chairman",
        description: "Mr. N. Chandrasekaran serves as Chairman of the board of Tata Sons, the holding company and promoter of more than 100 Tata operating companies with aggregate annual revenues of more than US $150 billion. He joined the board of Tata Sons in October 2016 and was appointed Chairman in January 2017. His appointment as Chairman of Tata Sons followed a 30-year career at Tata Consulting Services. Mr. Chandrasekaran rose through the ranks to become the CEO and under his leadership, TCS consolidated its position as the largest private sector employer in India and India’s most valuable company.Since he has taken over as Chairman of Tata Sons, Mr. Chandrasekaran has been driving transformation of the group towards digital, sustainability and supply chain resilience. The group has forayed into new businesses including electronics manufacturing, semiconductor, EV battery manufacturing, consumer internet platform, and mobile technology for 5G. The Tata group has expanded its aviation presence with the acquisition of Air India and is building a large global airline. Mr. Chandrasekaran was conferred with the Padma Bhushan, one of the highest civilian awards in India, in the field of trade and industry in 2022. The French Government conferred him with Légion d’Honneur, the highest civilian award in France for his outstanding business successes and decisive contribution to strengthening Indo-French economic ties. President Eisenhower Global Award for Leadership by the Business Council for International Understanding (BCIU) was conferred to him in 2022. Mr. Chandrasekaran is the Co-Chair of the US India CEO Forum. He is on the Board of Governors of New York Academy of Sciences, elected as an international member of the United States National Academy of Engineering (NAE), a member of the UTokyo Global Navigation Board, the Mitsubishi’s International Advisory Committee and International Advisory Council of Singapore’s Economic Development Board. He is the Chairman of Indian Institute of Management, Lucknow as well as the President of the Court at Indian Institute of Science, Bengaluru. Mr. Chandrasekaran is also a member of the Stanford Doer School for Sustainability Advisory Council and the MIT CEO Advisory Board. Mr. Chandrasekaran is also the author of Bridgital Nation, a groundbreaking book on harnessing technological disruptions to bring Indians closer to their dreams.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png"  // Add image URL here
    },
    {
        name: "MR. P. B. BALAJI",
        designation: "(Non Independent) Director",
        description: "Mr. P.B. Balaji has been serving as the Group Chief Financial Officer of Tata Motors Limited (“TML”) since November 2017. He is a member of the Executive Committee of TML and plays a key role in TML Group’s profitable and sustainable growth journey. He is also on the boards of Jaguar Land Rover, Tata Motors Finance Group Tata Technologies, and Tata Consumer Products Ltd. With nearly three decades of experience in the corporate sector, Mr. Balaji is a seasoned global finance professional who has worked across the FMCG and Automotive industries. He started his career at Unilever in 1995, where he held different corporate finance and supply chain positions in India, Singapore, UK, and Switzerland, Prior to joining Tata Motors, he served as the Chief Financial Officer of Hindustan Unilever. Mr. Balaji holds a post-graduate degree in management from the Indian Institute of Management, Calcutta, and is an alumnus of the Indian Institute of Technology, Chennai.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png"  // Add image URL here
    },
    {
        name: "MR. SIRAJ CHAUDHRY",
        designation: "Independent Director",
        description: "Mr. Siraj Chaudhry is a renowned industry expert, innovator, thought leader, and prominent voice in the agriculture and food industry. He has collaborated extensively with various sectors, including the government, social sector, and industry, on various transformational and nation-building projects. He holds a degree in B.Com (Hons.) from Delhi University, Masters in International Business from Indian Institute of Foreign Trade With over 36 years of experience in building, acquiring, divesting, and turning around businesses, Mr. Chaudhry currently serves as the Chief Advisor and Non-Executive Chairman for SATS India. Previously, he was the Managing Director & CEO of NCML, where he played a pivotal role in expanding the company’s footprint across the country and diversifying its operations, establishing it as a trusted and preferred agri-supply chain and solutions provider. He was also the Chairman of Cargill India, the Indian arm of Cargill Inc., where he led the build and expansion of Cargill’s food business in India, making it a leading player in edible oils, flour, corn products, and food ingredients. During his tenure, Cargill’s animal nutrition business and global business services footprint in India saw significant growth. Mr. Chaudhry is credited with spearheading Cargill’s efforts in edible oil fortification, which was recognized by Fortune Magazine as a Change the World activity. In addition to serving as a Non- Executive Director & Chairman Board of NCML, Mr. Chaudhry is an Independent Director on the boards f several companies, including Tata Consumers Products Ltd., Tata Coffee Ltd., Dhanuka Agritech Ltd., Jubilant Ingrevia Ltd, Triveni Engineering and Industries Ltd, Bikaji Foods International Ltd., Dhanuka Agritech Ltd., and Carrier Airconditioning & Refrigeration Ltd, SATS (India) Co. Pvt Ltd, Air India SATS Airport Services Pvt Ltd. He is also a member of the non-statutory advisory council of AB InBev, India, Louis Dreyfus Company, and Stanton Chase India Mr. Chaudhry has previously served as an Independent Director on the Board of IndusInd Bank and as a member of CDC Group plc (now BII) Food & Agriculture Advisory Council. He has chaired the National Committee on Food Processing and served as the Co-chair of the National Committee for Agriculture at FICCI. Mr. Chaudhry has also chaired the Agriculture and Food Committees at the American Chamber of Commerce and US India Business Council in India.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png"  // Add image URL here
    },
    {
        name: "MR. BHARAT PURI",
        designation: "Independent Director",
        description:"Mr. Bharat Puri is the Managing Director of Pidilite Industries Limited since April 2015, having first joined the Board of Pidilite Industries Ltd as an Independent Director in 2008. With a proven track record as a successful global business leader, he has effectively built, motivated, and directed diverse teams across various regions in both developed and developing markets. He is graduate in Commerce from Punjab University and holds post-graduate diploma in Management (MBA) from IIM, Ahmedabad. Mr. Puri’s professional journey began at Asian Paints in 1982, where he started as a Sales & Marketing executive and eventually rose to the position of Head of Sales & Marketing. In 1998, he transitioned to Cadbury India, serving as Director of Sales & Marketing before being appointed as its Managing Director in 2002. Throughout his career, he has held several senior leadership positions in Sales, Marketing, and General Management at both regional and global levels. His last appointment was as the Global President of Chocolates, Gum, and Candy for Mondelez International.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png"  // Add image URL here
    },
    {
        name: "MS. SHIKHA SHARMA",
        designation: "Independent Director",
        description: "Ms. Shikha Sharma holds a degree in B.A (Hons.) in Economics, post-graduate diploma in Software Technology from National Center for Software Technology and Post Graduate Diploma in Management from IIM, Ahmedabad. With a wealth of experience in banking and insurance, she boasts an impressive track record. During her tenure, she successfully transformed Axis Bank Limited from a predominantly corporate lender to a bank with a robust retail deposit franchise and a well-balanced lending book. Ms. Sharma embarked on her career with ICICI Bank in 1980. She served as the MD and CEO of ICICI Personal Financial Services from May 1998 to December 2000. Subsequently, she held the position of Managing Director and CEO at ICICI Prudential Life Insurance Company from December 2000 to June 2009. She later became the Managing Director and CEO of Axis Bank from June 2009 to December 2018. Ms. Sharma has earned numerous accolades, including the CNBC TV18 Outstanding Businesswoman of the year, AIMA JRD TATA Corporate Leadership, and Business Standard’s Banker of the Year. She has also been recognized as one of the Top 20 Women in Finance-by-Finance Asia and one of the 50 most powerful women in business by Fortune. Ms. Sharma serves on the board of directors for several publicly listed companies, including Tata Consumer Products Limited, Tech Mahindra Limited, Mahindra & Mahindra Limited, Dr. Reddy’s Laboratories Limited, and Piramal Enterprises Limited and Mahindra Electric Automobile Limited. Additionally, she is an advisor /consultant to Piramal Enterprises Limited, Billionbrains Garage Ventures Private Limited, Bahaar Foundation – a unit of Akshati Charitable Trust, andGoogle India Digital Services Pvt Ltd and McKinsey & Company Singapore Pte Ltd. She is also a member of the Board of Governors of IIM, Lucknow.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png"  // Add image URL here
    },
    {
        name: "DR. K. P. KRISHNAN",
        designation: "Independent Director",
        description: "Dr. K.P. Krishnan retired from the Indian Administrative Service (IAS) on December 31st, 2019, after serving for 37 years. Through his career, he held various positions in the Government of Karnataka, the Government of India, and the World Bank, serving in departments dealing with agriculture, co-operatives, marketing, urban development and infrastructure, commercial taxes, and finance. He also held field positions such as District Collector Mangalore. During his time in the Government of India, he served as Secretary of the Ministry of Skill Development and Entrepreneurship from February 1st, 2017, to December 31st, 2019, as Additional Secretary of the Department of Land Resources, Ministry of Rural Development (2014-2017), Additional Secretary of the Department of Economic Affairs, Ministry of Finance (2013-2014), Secretary of the Prime Minister’s Economic Advisory Council (2010-2012), and Joint Secretary of the Department of Economic Affairs, Ministry of Finance (2005-2010). In these roles, he served on the boards of corporations, banks, and statutory regulatory authorities. Dr. Krishnan has also been actively involved in research and academia throughout his government career. He has been a visiting faculty member at various institutions, including IIM Bangalore, ISB, and Ashoka University, and was the Bok Visiting Professor of Regulation at the University of Pennsylvania Law School in 2012-13. He served as the IEPF Chair Professor of Economics at the National Council of Applied Economic Research (NCAER) in New Delhi from August 7th, 2020, to December 31st, 2021, and is currently an Honorary Research Professor at the Centre for Policy Research (CPR) in New Delhi. Dr. Krishnan is also an Independent Director on the Boards of Shriram Capital Private Limited and Dr. Reddy’s Laboratories Limited. He studied Economics at St. Stephens College and Law at the Campus Law Centre, University of Delhi, and earned his FPM (Ph.D.) in Economics at IIM Bangalore’s 2003 graduation ceremony.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png"  // Add image URL here
    },
    // Add more team member objects here
    {
        name: "MR. SIRAJ CHAUDHRY",
        designation: "Independent Director",
        description: "Mr. Siraj Chaudhry is a renowned industry expert, innovator, thought leader, and prominent voice in the agriculture and food industry. He has collaborated extensively with various sectors, including the government, social sector, and industry, on various transformational and nation-building projects. He holds a degree in B.Com (Hons.) from Delhi University, Masters in International Business from Indian Institute of Foreign Trade With over 36 years of experience in building, acquiring, divesting, and turning around businesses, Mr. Chaudhry currently serves as the Chief Advisor and Non-Executive Chairman for SATS India. Previously, he was the Managing Director & CEO of NCML, where he played a pivotal role in expanding the company’s footprint across the country and diversifying its operations, establishing it as a trusted and preferred agri-supply chain and solutions provider. He was also the Chairman of Cargill India, the Indian arm of Cargill Inc., where he led the build and expansion of Cargill’s food business in India, making it a leading player in edible oils, flour, corn products, and food ingredients. During his tenure, Cargill’s animal nutrition business and global business services footprint in India saw significant growth. Mr. Chaudhry is credited with spearheading Cargill’s efforts in edible oil fortification, which was recognized by Fortune Magazine as a Change the World activity. In addition to serving as a Non- Executive Director & Chairman Board of NCML, Mr. Chaudhry is an Independent Director on the boards f several companies, including Tata Consumers Products Ltd., Tata Coffee Ltd., Dhanuka Agritech Ltd., Jubilant Ingrevia Ltd, Triveni Engineering and Industries Ltd, Bikaji Foods International Ltd., Dhanuka Agritech Ltd., and Carrier Airconditioning & Refrigeration Ltd, SATS (India) Co. Pvt Ltd, Air India SATS Airport Services Pvt Ltd. He is also a member of the non-statutory advisory council of AB InBev, India, Louis Dreyfus Company, and Stanton Chase India Mr. Chaudhry has previously served as an Independent Director on the Board of IndusInd Bank and as a member of CDC Group plc (now BII) Food & Agriculture Advisory Council. He has chaired the National Committee on Food Processing and served as the Co-chair of the National Committee for Agriculture at FICCI. Mr. Chaudhry has also chaired the Agriculture and Food Committees at the American Chamber of Commerce and US India Business Council in India.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png"  // Add image URL here
    },
    {
        name: "MR. DAVID CREAN",
        designation: "Independent Director",
        description: "Mr. David Crean is a highly accomplished and experienced professional in the food industry with over 35 years of expertise in leadership, talent development, innovation, research and development, science, quality management, and food safety. He is graduated with a BA (Hons.) Degree in Applied Biology from Liverpool Polytechnic. He held multiple senior leadership positions at Mars Incorporated, including, when he retired, the dual roles of Vice President of Corporate R&D and Chief Science Officer, where he contributed significantly to the Company’s strategy. Throughout his career, he led business growth initiatives, established global technology and research platforms,and most recently established various governance processes and performance standards for Mars’ global businesses. He launched over 70 Mars products in multiple geographies and drove profitable business growth across emerging and developed markets. Mr. Crean’s passion and leadership have guided Mars’ highly principled approach to science, research practices, policies, innovation, quality and food safety standards. Mr. Crean’s contributions extend beyond Mars as he participated in many events organised by the United Nations FAO and WHO while advocating for food security and safety. Since he retired from Mars in 2021, he has continued to share his knowledge and expertise, serving as Chair of the Global Food Safety Initiatives (GFSI) Science and Technology Advisory Group and advising numerous global businesses and start-ups.",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png" 
    },
    {
        name: "MR. SUNIL D’SOUZA",
        designation: "Managing Director & CEO",
        description: "Mr. Sunil D’Souza has been serving as the Managing Director & Chief Executive Officer of Tata Consumer Products since April 2020. Prior to this, he held the position of Managing Director at Whirlpool India Ltd. for over four years and had a significant contribution in transforming the Whirlpool business in India. He has also worked with PepsiCo for almost 15 years, where he held various leadership positions, managing the commercial aspects of the company’s food and beverage portfolio, and steering the business in a large cluster of Asian countries. Mr. D’Souza started his career with Hindustan Unilever in 1993 and has 30 years of extensive experience in the consumer products sector with a strong emphasis on strategy, growth, and execution.In addition to his current role as Managing Director & Chief Executive Officer of the Company, he is also a Director on the Board of Tata Starbucks Limited, Capital Foods Private Limited, NourishCo Beverages Limited, Tata Consumer Soulfull Private Limited, Organic India Private Limited and several of Tata Consumer Products’ overseas subsidiaries. Mr. D’Souza holds a degree in engineering from the University of Madras and is an alumnus of the Indian Institute of Management, Calcutta (IIM-C).   ",
        imgSrc: "./img/Tatahome/Artboard 5@3x.png" 
    },
    // Example: { name: "Jane Doe", designation: "CEO", description: "Description here", imgSrc: "image_url" }
];

// Function to create team member card
function createTeamCard(member, index) {
    console.log("i'm being called");
    const cardDiv = document.createElement('div');
    cardDiv.className = 'card-team container';
    
    if(index==0){
        cardDiv.style.top = `${150}px`;
    }
    else {
        cardDiv.style.top = `${150 + (index * 30)/10}px`;
    }
    if(index%2==0&&index!==0){
        cardDiv.style.transform = `translateX(${(50 + (index * 30)/5)}px) rotate(${(50 + (index * 30))/30}deg)`;
    }
    else{
        cardDiv.style.transform = `translateX(${(50 + (index * 30))/5}px) rotate(${-(50 + (index * 30))/30}deg)`;
    }
    


    const imgDiv = document.createElement('div');
    imgDiv.className = 'img-div col-5';

    const img = document.createElement('img');
    img.src = member.imgSrc;
    img.alt = member.name;

    const aboutTextDiv = document.createElement('div');
    aboutTextDiv.className = 'about-text-team w-100';

    const nameH3 = document.createElement('h3');
    nameH3.className = 'name-team';
    nameH3.textContent = member.name;

    const designationP = document.createElement('p');
    designationP.className = 'designation';
    designationP.textContent = member.designation;

    const descpDiv = document.createElement('div');
    descpDiv.className = 'descp-team p-2 col-7';
    descpDiv.textContent = member.description;

    aboutTextDiv.appendChild(nameH3);
    aboutTextDiv.appendChild(designationP);
    imgDiv.appendChild(img);
    imgDiv.appendChild(aboutTextDiv);
    cardDiv.appendChild(imgDiv);
    cardDiv.appendChild(descpDiv);

    return cardDiv;
}

// Function to render all team members
function renderTeamMembers() {
    const teamContainer = document.getElementById('teamContainer');
    teamMembers.forEach((member, index) => {
        const teamCard = createTeamCard(member, index);
        teamContainer.appendChild(teamCard);
    });
    renderTeamMembers2();
}
function renderTeamMembers2() {
    const teamContainer = document.getElementById('teamContainer-2');
    teamMembers.forEach((member, index) => {
        const teamCard = createTeamCard(member, index);
        teamContainer.appendChild(teamCard);
    });
}
window.onload=renderTeamMembers;